### ISSUE TITLE
Improved version of the paper

### ISSUE THREAD

**Issue by jerofad** [Biuuuuuuuu/Super-Interpolation#1]
Hi thanks for sharing your code on this implementation. I want to know if you have considered the new version of this paper which is **"Single Image Super-Resolution Using Global Regression Based on Multiple Local Linear Mappings"** [found here ](https://ieeexplore.ieee.org/document/7812796).

I am also wondering if you have implemented this code in python. Mathematica is behind a paywall and can't use it.

**Comment by senpai-a** [comment]
sorry but Im not planning to implement the GLM-SI algorithm and I dont have a py implementation of this code. I recommend u to check out the py implementation of RAISR in [this repo](https://github.com/JalaliLabUCLA/Jalali-Lab-Implementation-of-RAISR) which is similar to SI  so it would be rather easy to modify  it and get a SI or GLM-SI implementaion
